import { readFileSync, writeFileSync } from 'node:fs';
import { feature } from 'topojson-client';
import { geoAlbersUsa, geoPath } from 'd3-geo';

const W = 960, H = 560;
const topo = JSON.parse(readFileSync('src/modules/world/client/lib/us-states-10m.json', 'utf8'));
const fc: any = feature(topo, topo.objects.states);
const projection = geoAlbersUsa().fitSize([W, H], fc);
const path = geoPath(projection);

const FIPS_TO_STATE: Record<string, { name: string; abbr: string }> = {
  '01':{name:'Alabama',abbr:'AL'},'02':{name:'Alaska',abbr:'AK'},'04':{name:'Arizona',abbr:'AZ'},'05':{name:'Arkansas',abbr:'AR'},'06':{name:'California',abbr:'CA'},'08':{name:'Colorado',abbr:'CO'},'09':{name:'Connecticut',abbr:'CT'},'10':{name:'Delaware',abbr:'DE'},'11':{name:'D.C.',abbr:'DC'},'12':{name:'Florida',abbr:'FL'},'13':{name:'Georgia',abbr:'GA'},'15':{name:'Hawaii',abbr:'HI'},'16':{name:'Idaho',abbr:'ID'},'17':{name:'Illinois',abbr:'IL'},'18':{name:'Indiana',abbr:'IN'},'19':{name:'Iowa',abbr:'IA'},'20':{name:'Kansas',abbr:'KS'},'21':{name:'Kentucky',abbr:'KY'},'22':{name:'Louisiana',abbr:'LA'},'23':{name:'Maine',abbr:'ME'},'24':{name:'Maryland',abbr:'MD'},'25':{name:'Massachusetts',abbr:'MA'},'26':{name:'Michigan',abbr:'MI'},'27':{name:'Minnesota',abbr:'MN'},'28':{name:'Mississippi',abbr:'MS'},'29':{name:'Missouri',abbr:'MO'},'30':{name:'Montana',abbr:'MT'},'31':{name:'Nebraska',abbr:'NE'},'32':{name:'Nevada',abbr:'NV'},'33':{name:'New Hampshire',abbr:'NH'},'34':{name:'New Jersey',abbr:'NJ'},'35':{name:'New Mexico',abbr:'NM'},'36':{name:'New York',abbr:'NY'},'37':{name:'North Carolina',abbr:'NC'},'38':{name:'North Dakota',abbr:'ND'},'39':{name:'Ohio',abbr:'OH'},'40':{name:'Oklahoma',abbr:'OK'},'41':{name:'Oregon',abbr:'OR'},'42':{name:'Pennsylvania',abbr:'PA'},'44':{name:'Rhode Island',abbr:'RI'},'45':{name:'South Carolina',abbr:'SC'},'46':{name:'South Dakota',abbr:'SD'},'47':{name:'Tennessee',abbr:'TN'},'48':{name:'Texas',abbr:'TX'},'49':{name:'Utah',abbr:'UT'},'50':{name:'Vermont',abbr:'VT'},'51':{name:'Virginia',abbr:'VA'},'53':{name:'Washington',abbr:'WA'},'54':{name:'West Virginia',abbr:'WV'},'55':{name:'Wisconsin',abbr:'WI'},'56':{name:'Wyoming',abbr:'WY'},
};

const paths: Record<string,string> = {};
const centroids: Record<string,[number,number]> = {};
for (const f of fc.features) {
  const fips = String(f.id).padStart(2,'0');
  const d = path(f);
  if (!d) continue;                       // geoAlbersUsa clips territories to null — skipped, land in tray
  paths[fips] = d;
  const c = path.centroid(f);
  centroids[fips] = [Math.round(c[0]*10)/10, Math.round(c[1]*10)/10];
}

const out = `// GENERATED by scripts/generate-us-state-paths.ts — do not edit by hand.
// Regenerate: pnpm gen:map
export const US_MAP_VIEWBOX = '0 0 ${W} ${H}';
export const US_STATE_PATHS: Record<string,string> = ${JSON.stringify(paths)};
export const US_STATE_CENTROIDS: Record<string,[number,number]> = ${JSON.stringify(centroids)};
export const FIPS_TO_STATE: Record<string,{name:string;abbr:string}> = ${JSON.stringify(FIPS_TO_STATE)};
`;
writeFileSync('src/modules/world/client/lib/usStatePaths.ts', out);
console.log('wrote usStatePaths.ts —', Object.keys(paths).length, 'states');
