import { Router } from 'express';
import healthRouter from './health';
import agentsRouter from '@modules/agents/server/routes/agents';
import agentProfileRouter from '@modules/agents/server/routes/agentProfile';
import campaignsRouter from '@modules/elections/server/routes/campaigns';
import votesRouter from '@modules/legislation/server/routes/votes';
import legislationRouter from '@modules/legislation/server/routes/legislation';
import electionsRouter from '@modules/elections/server/routes/elections';
import governmentRouter from '@modules/government/server/routes/government';
import partiesRouter from '@modules/elections/server/routes/parties';
import activityRouter from '@modules/agents/server/routes/activity';
import decisionsRouter from '@modules/legislation/server/routes/decisions';
import adminRouter from '@modules/admin/server/routes/admin';
import providersRouter from '@modules/admin/server/routes/providers';
import profileRouter from '@modules/admin/server/routes/profile';
import searchRouter from './search';
import calendarRouter from './calendar';
import forumRouter from '@modules/forum/server/routes/forum';
import courtRouter from '@modules/legislation/server/routes/court';
import ticksRouter from './ticks';
import demosRouter from '@modules/benchmark/server/routes/demos';
import researcherRouter from '@modules/admin/server/routes/researcher';
import benchmarkRouter from '@modules/benchmark/server/routes/benchmark';

const router = Router();

router.use(healthRouter);
router.use(agentProfileRouter);
router.use(agentsRouter);
router.use(campaignsRouter);
router.use(votesRouter);
router.use(legislationRouter);
router.use(electionsRouter);
router.use(governmentRouter);
router.use(partiesRouter);
router.use(activityRouter);
router.use(decisionsRouter);
router.use(adminRouter);
router.use(providersRouter);
router.use(profileRouter);
router.use(searchRouter);
router.use(calendarRouter);
router.use(forumRouter);
router.use(courtRouter);
router.use(ticksRouter);
router.use(demosRouter);
router.use(researcherRouter);
router.use(benchmarkRouter);

export default router;
